services:
  db:
    container_name: discordllmbot-db
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    container_name: discordllmbot-bot
    build: .
    volumes:
      - ./bot:/usr/src/app/bot
      - ./shared:/usr/src/app/shared
    command: npm run dev:container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  pgadmin:
    container_name: discordllmbot-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /tmp/servers.json
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./config/pgadmin/servers.json:/tmp/servers.json

  docs:
    container_name: discordllmbot-docs
    build:
      context: .
      dockerfile: Dockerfile.docs
    volumes:
      - ./docs/src:/usr/src/docs/src
    ports:
      - "5173:5173"

  api:
    container_name: discordllmbot-api
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/usr/src/app/api
      - ./shared:/usr/src/app/shared
    command: npm run dev
    ports:
      - "${API_PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  dashboard:
    container_name: discordllmbot-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    volumes:
      - ./app:/usr/src/app
    ports:
      - "${DASHBOARD_PORT}:5173"
    depends_on:
      - api
    env_file:
      - ./.env